### ISSUE TITLE
[Moflon IDE] [TGG] Model Sync with Eclipse Modeleditor

### ISSUE THREAD

**Issue by Arikae** [eMoflon/emoflon-issue-tracking-system#426] opened 2015-05-11 15:14 UTC
It would be very nice to have a model editor that keeps track on occured model alterations, (running OnlineDeltaCreator in background) (+ application of them via a button?)
It remains to be investigated further what should happen if the editor is closed (saving old deltas if not yet applied or apply them directly?).

**Comment by anthonyanjorin** [comment] 2015-08-11 14:56
This is a duplicate of **Delta creating emf model editor #413**

**Closed** 2015-08-11 14:56 UTC
Labels: eMoflon-IDE, eMoflon-TGG, feature-request
