### ISSUE TITLE
[Validation][Democles] A StoryPattern with a free ObjectVariable without any releation is validated and creates wrong/no Code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eMoflon/emoflon-issue-tracking-system#261] opened 2015-03-14 18:22 UTC
```
What steps will reproduce the problem?
1. get the DemoclesTestWorkspace
2. copy the atteched Democles_0.eap in the specification project of the 
Workspace
3. validate and export the eap
4. go to the Project OnlineSocialNetwork to the model folder and validate the 
ecore file

What is the expected output? What do you see instead?
I expect:
A Kind of an Error or Exception, which tells me this is wrong.
Or
A Code Workaround (but error message is prefered)
I get:
No Errors from eMoflon only an error in the Code because a pattern in democles 
is not created

Please use labels and text to provide additional information.
the wrong StoryPattern is in 
OnlineSocialNetwork/Members.addFriends(friend:Member)/isAlreadyAFriend

https://www.dropbox.com/s/wb3m8pkqebu58nn/Democles_0.eap?dl=0

```

Original issue reported on code.google.com by `zniper1...@googlemail.com` on 7 Nov 2014 at 4:59

**Comment by gervarro** [comment] 2015-05-21 17:22
This issue has been fixed with a high probability since November 2014. At least I could not reproduce the problem on May 21st, 2015.

**Closed by gervarro** 2015-05-21 17:22 UTC
Labels: eMoflon-Democles, eMoflon-Validation
