### ISSUE TITLE
Problem on eMoflon build

### ISSUE THREAD

**Issue by mabilov** [eMoflon/emoflon-issue-tracking-system#414] opened 2015-05-07 09:43 UTC
When I am trying to build TGG I a getting an error:
'eMoflon Building' has encountered a problem.
Internal exception occured (probably caused by a bug in the validation module): Pattern matching in node [BasicSyntacticCheck] failed Please report the bug on https://code.google.com/p/emoflon-issue-tracking-system/
Pattern matching in node [BasicSyntacticCheck] failed.
![bug](https://cloud.githubusercontent.com/assets/1804125/7512578/49554006-f4ae-11e4-9645-806ed40e9c9e.png)

**Comment by RolandKluge** [comment] 2015-05-07 09:46
Could you provide us with the EAP file that contains the meta-model on which the code generation fails?

**Comment by mabilov** [comment] 2015-05-07 10:00
The problem occurs on building "UseCaseToModalSequenceDiagramIntegration" project. Here is a link to eap file:
https://www.dropbox.com/s/zvzhxqumaxnu13k/MetaAndTgg.eap?dl=0

**Comment by RolandKluge** [comment] 2015-05-07 10:42
I will have a look at your project, but just one hint in advance: eMoflon offers to validate Ecore files. You may trigger the validation by right-clicking an Ecore file. Afterwards select *eMoflon --> Validate*.

**Comment by mabilov** [comment] 2015-05-07 15:13
I receive the same exception on validation of my ecore file:
'SDM vaildation on project UseCaseToModalSequenceDiagramIntegration' has encountered a problem.

Internal exception occured (probably caused by a bug in the validation module): Pattern matching in node [BasicSyntacticCheck] failed Please report the bug on https://code.google.com/p/emoflon-issue-tracking-system/
Pattern matching in node [BasicSyntacticCheck] failed
![bug1](https://cloud.githubusercontent.com/assets/1804125/7518605/4f077f40-f4dc-11e4-8100-fa8ab6776c5a.png)

**Comment by RolandKluge** [comment] 2015-05-07 16:08
I could not reproduce the problem with my version of eMoflon, which means you will probably need a more recent version. Which one do you have installed on your system?

**Comment by mabilov** [comment] 2015-05-07 16:12
I have 1.0.0.201204221604

**Comment by RolandKluge** [comment] 2015-05-07 16:14
Ok, this seems to be a beta build. We plan to create a new beta release in the next days so have to ask you to wait a little and then you may try the new beta.

**Comment by mabilov** [comment] 2015-05-07 16:17
Anthony shared "deployment" folder with me in dropbox. Would you update it there?

**Comment by RolandKluge** [comment] 2015-07-24 21:44
I guess I may close this issue.

**Closed by RolandKluge** 2015-07-24 21:44 UTC
