### ISSUE TITLE
DotToTGGTGG throws Runtime Exception

### ISSUE THREAD

**Issue by SvenPeldszus** [eMoflon/emoflon-issue-tracking-system#549] opened 2015-08-12 12:29 UTC
It is currently not possible to convert XMI files into the dot representation. In the installed eMoflon Plugin just a NullpointerException is visible:

```14:12:09 ERROR [ui.ConvertToDotHandler::186] - java.lang.NullPointerException during visualization: null```

However, in the Developer Workspace we can see that the NullpointerException has its origin in the Dot TGG throwing the attached Runtime Exception.

@erhanleblebici This looks for me similar to the TGG bug where two enumerations did not match you fixed for me on Friday, August 7th.

P.S. While searching for the  reasons of the exception I've taken the chance to override the  ```-getAbsolutePathToDotExe():string``` method in ```ConvertToDotHandler.java``` to check the default locations of Graphviz Dot and the environment variable before using your provided ```dot.exe``` as fallback on Windows. If desired I can provide a patch. 

```
java.lang.RuntimeException: java.lang.RuntimeException: Pattern matching in node [prepare return value] failed. Variables: [this] = DotToTGGTGG.Rules.impl.NodeToSrcOVImpl@131f200b.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.moflon.tgg.algorithm.synchronization.Synchronizer.collectDerivations(Synchronizer.java:243)
	at org.moflon.tgg.algorithm.synchronization.Synchronizer.handleAdditions(Synchronizer.java:135)
	at org.moflon.tgg.algorithm.synchronization.Synchronizer.synchronize(Synchronizer.java:116)
	at org.moflon.tgg.algorithm.synchronization.SynchronizationHelper.performSynchronization(SynchronizationHelper.java:434)
	at org.moflon.tgg.algorithm.synchronization.SynchronizationHelper.integrateBackward(SynchronizationHelper.java:460)
	at org.moflon.visualization.ui.ConvertToDotHandler.modelToTree_TGG(ConvertToDotHandler.java:295)
	at org.moflon.visualization.ui.ConvertToDotHandler.modelToDot(ConvertToDotHandler.java:216)
	at org.moflon.visualization.ui.ConvertToDotHandler.execute(ConvertToDotHandler.java:87)
	at org.moflon.visualization.ui.ConvertToDotHandler.execute(ConvertToDotHandler.java:72)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:799)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:675)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:659)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:592)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1327)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: java.lang.RuntimeException: Pattern matching in node [prepare return value] failed. Variables: [this] = DotToTGGTGG.Rules.impl.NodeToSrcOVImpl@131f200b.
	at DotToTGGTGG.Rules.impl.NodeToSrcOVImpl.isAppropriate_BWD_EMoflonEdge_64(NodeToSrcOVImpl.java:431)
	at DotToTGGTGG.Rules.impl.NodeToSrcOVImpl.eInvoke(NodeToSrcOVImpl.java:789)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eInvoke(BasicEObjectImpl.java:2027)
	at org.moflon.tgg.algorithm.invocation.InvokeUtil.invokeOperationWithSingleArg(InvokeUtil.java:27)
	at org.moflon.tgg.algorithm.invocation.InvokeIsAppropriate.lambda$0(InvokeIsAppropriate.java:41)
	at org.moflon.tgg.algorithm.invocation.InvokeIsAppropriate$$Lambda$39/1738821325.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by anthonyanjorin** [comment] 2015-08-12 17:17
So I've tried the visualization with a few other files.  It is still working in general I would say.  Must be something with your particular TGG (you were visualizing a TGG right?) I would say.

Can you provide the necessary files here so I can try it out?  If it is related to what @erhanleblebici fixed, maybe that (whatever it was) is also the reason here?

**Comment by SvenPeldszus** [comment] 2015-08-12 17:39
I forgot to mention that I am currently on the latest stable release (eMoflon Core (required)	- 2.0.0.201508071539). I can reproduce the error on multiple systems and for all files I've tried.

Some of those files I've uploaded to the issues folder in the file ```issue542_DotToTGGTGG_throws_Runtime_Exception.zip```

I got a similar looking exception for my TGGs. There was something, mixed up with Forward_Backward mode.

**Comment by anthonyanjorin** [comment] 2015-08-12 19:15
There is no such file in the issues folder

**Comment by anthonyanjorin** [comment] 2015-08-12 19:21
Just found out that our Release is currently newer than our beta ;)
So maybe I can now reproduce the error...

**Comment by SvenPeldszus** [comment] 2015-08-12 19:26
Sorry, I had overseen a merge I had to confirm.

**Comment by RolandKluge** [comment] 2015-08-12 19:28
NB: We should create a beta with the most urgent fixes, soon.

**Comment by anthonyanjorin** [comment] 2015-08-12 20:36
ok so its the same problem as @erhanleblebici already found.  Lars should be able to fix this soon.

**Comment by anthonyanjorin** [comment] 2015-08-18 19:56
implemented an ugly fix for this (always create eoperations but only activities if application type fits)

**Closed by anthonyanjorin** 2015-08-18 19:56 UTC
