### ISSUE TITLE
[Moflon IDE] Improve visualization by allowing filtering of rules

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#392] opened 2015-04-22 16:53 UTC
Currently, the visualization just visualizes everything it finds.

This might be ok for TGGs, but the generated transformation can consist of really many SDMs (i.e. viz takes quite a while or even runs out of heap space).

Yes we should improve the algorithm -- a pragmatic solution for the time being would be to allow the user to give a filter (reg exp) in a dialogue before the visualization runs.  Only SDMs of with matching rule names should be visualized.

**Comment by anthonyanjorin** [comment] 2015-06-12 13:03
Some other ideas for viz configuration:

* Should .dot files be deleted?
* 3 diagrams for TGGs instead of one?
* ???

**Comment by anthonyanjorin** [comment] 2015-06-12 13:04
Might also be the right time to think about other visualisations:

* Precedence graph? 
* Sync protocol?
* ???

**Comment by anthonyanjorin** [comment] 2015-07-15 08:34
@erhanleblebici FYI

**Comment by Arikae** [comment] 2015-08-20 19:39
Done.

**Comment by anthonyanjorin** [comment] 2015-08-21 08:15
So tried it out:

* The choice of methods is not updated (live), depending on the regexp.  This makes it really hard to know if the regexp is as one wants it to be
* Every regexp I entered was simply ignored and everything was visualized.  I tried quite a lot, also very trivial regexps.  Nothing seems to work.

**Comment by Arikae** [comment] 2015-08-21 12:22
Added example that shows how to use this dialog but I wasn't able to reproduce the error.
From my point of view I'd say that the issue can be closed.
Maybe the problem was already resolved by filtering those items that are not implemented via SDMs.
Close?

**Closed** 2015-08-21 13:05 UTC
Labels: eMoflon-IDE
